---
production: &default
  serverPort: 2222
  baseUrl: http://www.carlossantanar.com
  cookieDomain: .carlossantanar.com
  views:
    minify: true
    lessPrecompile: true
  html:
    engine: handlebars
    extension: .hbs
    layout: main
  redis:
    host: localhost
    port: 6379
  controllers:
    default: home
    blog:
      postPerPage: 12
  languages:
    default: en
    list: [en, es, fr, pt, ge, jp, ch]
  security:
    secret: c4rl0sSant4naR.com
  database:
    mysql:
      host: 127.0.0.1
      user: root
      password:
      database: carlossantanar
      port: 3306
      debug: true
      socket: /var/mysql/mysql.sock
    mongodb:
      uri: mongodb://localhost/
      database: carlossantanar

stage: &stage
  <<: *default
  baseUrl: http://stage.carlossantanar.com

latest: &latest
  <<: *stage
  baseUrl: http://latest.carlossantanar.com

development:
  <<: *latest
  baseUrl: http://local.carlossantanar.com
  views:
    minify: false
    lessPrecompile: false
